### ISSUE TITLE
Crash when adding a node server

### ISSUE THREAD

**Issue by jimboca** [Einstein42/udi-polyglotv2#1]
Last night I deleted a test server, and tried to add it back and it crashed.  I'm running the latest I pulled from github yesterday.  Also, would be nice to show a more detailed version number in the log so you know what version we are running?

```
10/19/2017, 6:16:50 PM - info: MQTT: Subscribe Successful udi/polyglot/connections/# QoS: 0
10/19/2017, 6:16:50 PM - info: MQTT: Subscribe Successful udi/polyglot/ns/10 QoS: 0
10/19/2017, 6:16:50 PM - info: v2a(10): - NodeServer found on ISY with the name v2a. Checking for Nodes...
10/19/2017, 6:16:50 PM - info: v2a(10): Completed ReSync with ISY.
10/19/2017, 6:19:21 PM - info: Successful login by admin
10/19/2017, 6:19:24 PM - info: MQTT: Frontend Websockets interface  Connected.
10/19/2017, 6:19:54 PM - info: v2a(10): attempting to delete NodeServer v2a
10/19/2017, 6:19:54 PM - info: v2a(10): deleting v2a's nodes from ISY.
10/19/2017, 6:19:56 PM - info: v2a(10): Succesfully removed NodeServer. You must reboot the ISY.
10/19/2017, 6:20:17 PM - info: MQTT: Frontend Websockets interface  Disconnected.
10/19/2017, 6:20:18 PM - info: MQTT: Frontend Websockets interface  Connected.
10/19/2017, 6:20:44 PM - info: MQTT: Frontend Websockets interface  Disconnected.
10/19/2017, 6:22:27 PM - info: Successful login by admin
10/19/2017, 6:22:29 PM - info: MQTT: Frontend Websockets interface  Connected.
10/20/2017, 7:28:05 AM - info: MQTT: Frontend Websockets interface  Disconnected.
10/20/2017, 5:58:48 PM - info: MQTT: Frontend Websockets interface  Connected.
10/20/2017, 6:00:33 PM - info: v2a(10): Attempting to install v2a NodeServer into ISY.
10/20/2017, 6:00:33 PM - info: v2a(10): Installed into ISY sucessfully. Reboot the ISY and upload the profile.zip
10/20/2017, 6:00:34 PM - info: Registered new NodeServer: v2a(10)
10/20/2017, 6:00:34 PM - error: uncaughtException: Cannot read property 'topic' of undefined date=Fri Oct 20 2017 18:00:34 GMT-0700 (PDT), pid=20146, uid=1000, gid=1000, cwd=/, execPath=/usr/local/bin/node, version=v6.11.0, argv=[/usr/local/bin/node, /usr/local/bin/polyglot-v2], rss=49582080, heapTotal=29347840, heapUsed=23672072, external=18444402, loadavg=[0.013671875, 0.1103515625, 0.1015625], uptime=173448
TypeError: Cannot read property 'topic' of undefined
    at Client.subscribe (/usr/local/lib/node_modules/polyglot-v2/lib/modules/mqtt.js:106:59)
    at MqttClient.subscribe (/usr/local/lib/node_modules/polyglot-v2/node_modules/mqtt/lib/client.js:484:5)
    at Object.addSubscription (/usr/local/lib/node_modules/polyglot-v2/lib/modules/mqtt.js:101:16)
    at newNodeServer.save (/usr/local/lib/node_modules/polyglot-v2/lib/models/nodeserver.js:191:14)
    at /usr/local/lib/node_modules/polyglot-v2/node_modules/mongoose/lib/model.js:3764:16
    at /usr/local/lib/node_modules/polyglot-v2/node_modules/mongoose/lib/services/model/applyHooks.js:150:20
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
10/20/2017, 6:00:37 PM - info: Polyglot shutdown complete with code: 1
10/20/2017, 6:00:58 PM - info: Starting Polyglot version 2.0
10/20/2017, 6:01:00 PM - info: MongoDB: Connected
10/20/2017, 6:01:08 PM - info: MQTT Services Started.
10/20/2017, 6:01:09 PM - info: Secure Server started on port 8080
10/20/2017, 6:01:09 PM - info: ISY: Got Version 5.0.10
10/20/2017, 6:01:10 PM - info: MQTT: Subscribe Successful udi/polyglot/connections/# QoS: 0
10/20/2017, 6:01:10 PM - info: MQTT: Subscribe Successful udi/polyglot/ns/10 QoS: 0
10/20/2017, 6:01:10 PM - info: v2a(10): - NodeServer found on ISY with the name v2a. Checking for Nodes...
10/20/2017, 6:01:10 PM - info: v2a(10): Completed ReSync with ISY.
10/20/2017, 6:01:30 PM - info: MQTT: Frontend Websockets interface  Connected.
```

**Comment by Einstein42** [comment]
This is fixed.
